### ISSUE TITLE
"Consulting" Service Page

### ISSUE THREAD

**Issue by robocopklaus** [21stdigital/21st.digital#18]
# Problem

Kunden und Interessenten fehlt eine dedizierte und umfassend informierende Seite, die unsere Consulting-Dienstleistungen beschreibt. Dies begrenzt unser Potenzial, die Kompetenzen und den Mehrwert unseres Unternehmens im Bereich Consulting effektiv zu kommunizieren.

# User Story

Als potenzieller Kunde möchte ich eine spezifische Seite über das Consulting-Angebot besuchen können, um detaillierte Informationen über die Beratungsansätze, Expertisebereiche, Methoden und Erfolgsgeschichten zu erfahren, damit ich die Eignung des Unternehmens für meine spezifischen Bedürfnisse beurteilen kann.

# Vorhaben

Entwicklung einer speziellen Seite für den Dienstleistungsbereich "Consulting", die unsere Beratungsphilosophie, -methoden und -kompetenzen detailliert darstellt. Diese Seite soll auch Informationen zu verschiedenen Consulting-Segmenten enthalten, die wir abdecken, und Beispiele von erfolgreichen Projekten und Kundenfeedback präsentieren.

# Abgrenzung

Diese Story konzentriert sich ausschließlich auf die Erstellung einer einzelnen Dienstleistungsseite für Consulting. Weitere Dienstleistungen oder allgemeine Unternehmensinformationen sind nicht Teil dieser Story.

# Akzeptanzkriterien

- Die Seite bietet eine umfassende Beschreibung unserer Consulting-Dienstleistungen, inklusive spezifischer Dienstleistungssegmente.
- Präsentation von Fallbeispielen und Projekt-Highlights, die unsere Expertise und Erfolge im Consulting-Bereich illustrieren.
- Integration von Kundenfeedback und Testimonials, die die Qualität und Zufriedenheit mit unseren Beratungsleistungen bestätigen.
- Ein klarer Handlungsaufruf (Call-to-Action) für eine Kontaktaufnahme oder Informationsanfrage ist vorhanden.
- Die Seite entspricht den Corporate Design-Vorgaben und ist benutzerfreundlich und intuitiv navigierbar.
- Die Seite ist responsiv gestaltet, um auf allen Endgeräten eine optimale Benutzererfahrung zu gewährleisten.

**Comment by JimSeven** [comment]
### Leistungen

Eventuell ist der Bereich Leistungen mit dem Tiles Modul bereits erst einmal umsetzbar:

![Image](https://github.com/user-attachments/assets/001143ff-46e0-42e7-9185-b259435eb8d7)

### Unser Ansatz

Hier könnte ich mir vorstellen, dass durch eine Einrückung und eine große Typo bei den Zahlen der Aufzählungen die Seite aufgelockert wird und die Seite insgesamt an Spannung gewinnt. Beispiel:

![Image](https://github.com/user-attachments/assets/ac7432af-85e9-4c33-9ea4-508bcad74190)

### Vorteile

Grober Vorschlage für die Auflistung der Vorteile:

![Image](https://github.com/user-attachments/assets/c40c002f-9050-4306-85a6-25ec17ca72d3)

**Comment by JimSeven** [comment]
Wireframe für einen **Service** am Beispiel von **Consulting**

[Wireframe Services.pdf](https://github.com/user-attachments/files/16415394/Wireframe.Services.pdf)
