### ISSUE TITLE
Enable Git LFS for Efficient Management of Images and Videos in the Repository

### ISSUE THREAD

**Issue by robocopklaus** [21stdigital/21st.digital#198]
# Problem

Derzeit werden Bilder und Videos direkt im Git Repository gespeichert, was zu einer erheblichen Erhöhung der Repository-Größe und einem ineffizienten Speicherverbrauch führt. Dies kann die Performance von Git-Operationen beeinträchtigen und den Speicherbedarf unnötig erhöhen.

# User Story

Als Entwickler möchte ich Git LFS (Large File Storage) aktivieren, um Bilder und Videos effizienter zu verwalten, Speicherplatz im Repository zu sparen und die Performance von Git-Operationen zu verbessern.

# Vorhaben

Aktivierung und Konfiguration von Git LFS für das Repository, sodass alle großen Dateien wie Bilder und Videos über Git LFS verwaltet werden. Dies umfasst die Migration der bereits vorhandenen großen Dateien in Git LFS und die Anpassung des Workflows, um sicherzustellen, dass neue Dateien ebenfalls über Git LFS verwaltet werden.

# Abgrenzung

Diese Story konzentriert sich auf die Implementierung von Git LFS und die Migration bestehender Dateien. Die Optimierung der Dateigrößen oder weiterer Speicherlösungen sind nicht Teil dieser Story.

# Akzeptanzkriterien

1. Git LFS ist im Repository aktiviert und konfiguriert.
2. Alle bestehenden Bilder und Videos sind erfolgreich in Git LFS migriert.
3. Neue große Dateien (Bilder, Videos) werden automatisch über Git LFS verwaltet.
4. Die Größe des Repositorys hat sich nach der Migration signifikant verringert.
5. Eine Dokumentation zur Nutzung von Git LFS ist vorhanden und für alle Teammitglieder zugänglich.

**Comment by Sm1lEE** [comment]
Alle Assets in `public/assets` liegen nun in Git LFS.
Die Historie habe ich so gesäubert, dass die Assets nicht mehr vorhanden sind. Das Repository sollte deshalb lokal komplett neu ausgecheckt werden, damit es keine Konflikte in den Git Histories gibt.
Eine Dokumentation zur Verwendung von Git LFS ist in der README.md hinterlegt.
