### ISSUE TITLE
Integrate DigitalOcean Spaces as Asset Storage in Statamic

### ISSUE THREAD

**Issue by robocopklaus** [21stdigital/21st.digital#235]
# Problem

Aktuell werden Assets wie Bilder und Videos im Git Repository mit Git LFS verwaltet, was die Repository-Größe erhöht und die Skalierbarkeit der Asset-Verwaltung einschränkt. Die Verwendung von DigitalOcean Spaces als Asset-Container könnte diese Probleme lösen und zusätzliche Vorteile bieten.

# User Story

Als Entwickler möchte ich DigitalOcean Spaces als Asset-Container in Statamic verwenden, um die Verwaltung von Bildern und Videos auszulagern, die Git Repository-Größe zu reduzieren und von den Skalierbarkeits- und Backup-Funktionen eines Cloud Storage zu profitieren.

# Vorhaben

Integration von DigitalOcean Spaces in Statamic als primäre Lösung für die Speicherung und Verwaltung von Assets. Dies umfasst die Konfiguration des Statamic CMS zur Nutzung von DigitalOcean Spaces für Assets und die Migration der bestehenden Dateien aus Git LFS zu DigitalOcean Spaces.

https://statamic.dev/tips/digital-ocean-spaces-for-asset-container

# Abgrenzung

Diese Story konzentriert sich auf die Integration von DigitalOcean Spaces und die Migration der bestehenden Assets. Die Optimierung des Workflows oder weiterer Backend-Änderungen sind nicht Teil dieser Story.

# Akzeptanzkriterien

- [x] DigitalOcean Spaces ist erfolgreich als Asset-Container in Statamic integriert.
- [x] Alle bestehenden Asset-Dateien (Bilder und Videos) sind von Git LFS zu DigitalOcean Spaces migriert.
- [x] Das Git Repository enthält keine Asset-Dateien mehr, was die Repository-Größe reduziert.
- [x] Die Website nutzt die Assets von DigitalOcean Spaces ohne Performance-Verlust oder Funktionsstörungen.
- [x] Die Skalierbarkeit der Asset-Verwaltung ist verbessert und ermöglicht die Nutzung von DigitalOcean Spaces-Funktionen wie automatische Backups.
- [x] Eine Dokumentation zur Nutzung von DigitalOcean Spaces als Asset-Container in Statamic ist vorhanden.

**Comment by Sm1lEE** [comment]
Im `next`-Branch wird nun ein DigitalOcean Space für die Assets verwendet.
