### ISSUE TITLE
Upgrade to Pest Version 3 and Develop a Unified Testing Standard with Arch Testing Features

### ISSUE THREAD

**Issue by JimSeven** [21stdigital/21st.digital#237]
# Problem

Unsere bestehende Testumgebung nutzt eine ältere Version von Pest, die nicht die neuesten Features und Verbesserungen enthält. Um die Codequalität und die Effizienz unserer Tests weiter zu optimieren, ist ein Upgrade auf Pest Version 3 erforderlich. Besonders die neuen Arch Testing Features, [die auf der Laracon US 2024 vorgestellt wurden](https://www.youtube.com/watch?v=BNhbgcNJyAk&t=1055s), bieten uns die Möglichkeit, unsere Tests besser zu strukturieren und Architektur-Regeln zu definieren und durchzusetzen.

Zudem fehlt uns ein einheitlicher Test-Standard, der sowohl für die Weiterentwicklung unserer bestehenden Laravel/Statamic Projekte als auch für zukünftige Projekte als Leitfaden dient. Eine gründliche Analyse der bestehenden Codebasis und die Entwicklung eines umfassenden Testkonzepts sind notwendig, um sicherzustellen, dass die Teststrategie effizient und skalierbar ist.

# User Story

Als Entwickler möchte ich Pest auf Version 3 aktualisieren, die neuen Arch Testing Features integrieren und einen Test-Standard entwickeln, um die Codequalität zu verbessern und eine konsistente Teststrategie für aktuelle und zukünftige Projekte zu gewährleisten.

# Vorhaben

**1. Upgrade von Pest:**

- Aktualisierung von Pest auf Version 3

- Sicherstellen, dass alle bestehenden Tests weiterhin funktionieren und keine Kompatibilitätsprobleme auftreten.

**2. Implementierung der neuen Arch Testing Features:**

- Integration der neuen default Arch Testing Features, wie sie auf der Laracon US 2024 vorgestellt wurden.

- Definition und Implementierung von Architekturregeln basierend auf den neuen Features.

- Anpassung der bestehenden Testfälle, wo nötig, um die neuen Arch Testing Features zu nutzen.

**3. Analyse und Konzeption von Teststrategien:**

- Analyse der bestehenden Laravel/Statamic Codebasis, um Bereiche zu identifizieren, in denen Tests sinnvoll und notwendig sind.

- Erstellen eines Testkonzepts, das die wichtigsten zu testenden Bereiche und geeignete Testarten definiert.

**4. Erarbeitung eines Test-Standards:**

- Entwicklung eines einheitlichen Test-Standards, der als Leitfaden für die Weiterentwicklung bestehender Projekte sowie für zukünftige Projekte dient.

# Abgrenzung

- Die Story umfasst die Aktualisierung auf Pest Version 3, die Implementierung der neuen Arch Testing Features, die Analyse der Codebasis, und die Entwicklung eines Test-Standards.

- Anpassungen an anderen Testframeworks oder die Einführung weiterer Tools sind nicht Teil dieses Scopes.

- Die Story beschränkt sich auf die Analyse und Konzeption innerhalb unserer bestehenden Laravel/Statamic Projekte.

# Akzeptanzkriterien

- Pest ist erfolgreich auf Version 3 aktualisiert, und alle Tests laufen fehlerfrei.

- Die neuen Arch Testing Features sind implementiert und mindestens eine Architekturregel ist definiert und getestet.

- Ein umfassendes Testkonzept für unsere Laravel/Statamic Projekte ist erstellt und dokumentiert.

- Ein einheitlicher Test-Standard ist entwickelt und dient als Leitfaden für zukünftige Projekte.

**Comment by robocopklaus** [comment]
@JimSeven spielt dieses issue #79 hier mit rein?

**Comment by JimSeven** [comment]
@robocopklaus oh ja, ich wusste doch das wir noch ein Ticket in der Richtung hatten. Das hatte ich nicht gefunden. Danke!
