### ISSUE TITLE
Implement Content Module for Page Section Header

### ISSUE THREAD

**Issue by JimSeven** [21stdigital/21st.digital#262]
<img width="654" alt="image" src="https://github.com/user-attachments/assets/262b4071-f2d3-4bac-9ac2-01d8aec7ded4">

<img width="656" alt="image" src="https://github.com/user-attachments/assets/ae4c2015-0a0a-4048-95db-6d9e9bef832a">

## Problem:
Es muss ein neues Modul implementiert werden, das verschiedene Inhalte gemäß den Designvorgaben strukturiert darstellt.

## User Story:
Als Redakteur möchte ich ein flexibles Content Modul haben, um Inhalte in verschiedenen Sektionen klar abgrenzen und strukturieren zu können.

## Vorhaben:
- Implementierung eines flexiblen Moduls zur Darstellung von Inhalten in Sektionen.
- Unterstützung für Titel und optionale Meta-Titel und einem optionalen kurz Text
- Das Modul gibt es in zwei Varianten: Links ausgerichtet und zentriert 

## Abgrenzung:
- Keine interaktiven Elemente.

## Akzeptanzkriterien:
- Inhalte können im CMS angepasst und korrekt im Frontend angezeigt werden.

**Comment by robocopklaus** [comment]
Wenn ich das Content Module auswähle im Backend und befülle, dann wird es nicht gerendert.
