### ISSUE TITLE
Implement Content Module for Case Study Teaser

### ISSUE THREAD

**Issue by JimSeven** [21stdigital/21st.digital#264]
<img width="525" alt="image" src="https://github.com/user-attachments/assets/4edf0986-715e-4a78-9f15-d3d89f180eca">

## Problem:
Ein neues Content Modul muss entwickelt werden, das gemäß dem vorliegenden Design strukturierten Inhalt auf der Website darstellt.

## User Story:
Als Redakteur möchte ich ein Modul haben, das verschiedene Arten von Inhalten zusammenfasst und als Vorschau darstellt.

## Vorhaben:
- Implementierung eines Moduls zur flexiblen Darstellung von Vorschauinhalten.
- Unterstützung von Text- und Bildelementen.

## Abgrenzung:
- Keine Interaktionen oder Animationen.

## Akzeptanzkriterien:
- Inhalte sind über das CMS anpassbar und werden korrekt im Frontend dargestellt.

**Comment by robocopklaus** [comment]
Wenn ich im Case Study Teaser im CMS `by Hand` auswähle, werden immer alle Case Studies angezeigt statt nur der ausgewählten
