### ISSUE TITLE
Implement Content Module for Logo Wall

### ISSUE THREAD

**Issue by JimSeven** [21stdigital/21st.digital#267]
<img width="526" alt="image" src="https://github.com/user-attachments/assets/23d7b87c-4681-4f2a-ba7c-0f4675552237">

## Problem:
Ein weiteres Content Modul muss zur strukturierten Darstellung von Inhalten entwickelt werden.

## User Story:
Als Redakteur möchte ich ein flexibles Modul haben, um mehrere Inhalte, die zur gleichen Kategorie gehören, visuell geordnet darzustellen.

## Vorhaben:
- Implementierung eines Moduls zur geordneten Darstellung von mehreren Inhaltselementen (Text oder Bilder).
- Anpassungsmöglichkeiten über das CMS.

## Abgrenzung:
- Keine Animation oder Interaktion.

## Akzeptanzkriterien:
- Inhalte sind vollständig über das CMS anpassbar und werden korrekt im Frontend dargestellt.

**Comment by robocopklaus** [comment]
- Hover-Effekt rausnehmen
- Logos sind insgesamt sehr groß. Vielleicht alles um 25% verkleinern?

## Low Prio

https://tailwindui.com/components/marketing/sections/logo-clouds#component-58e002f268559c7aba120b917e51ea65
Hattest Du nicht mal sowas ausprobiert?

![Image](https://github.com/user-attachments/assets/c82a7156-d61f-432a-8872-6266a578bf96)
