### ISSUE TITLE
Implement Content Module for Two Column Layout (Text Left, Content Right)

### ISSUE THREAD

**Issue by JimSeven** [21stdigital/21st.digital#272]
## Problem:
Ein flexibles Zwei-Spalten-Modul zur Darstellung von Inhalten muss implementiert werden.

## User Story:
Als Redakteur möchte ich ein flexibles Modul haben, das Inhalte in einem Zwei-Spalten-Layout anzeigt, um Informationen übersichtlich darzustellen.

## Vorhaben:
- Implementierung eines flexiblen Zwei-Spalten-Moduls zur Darstellung von Inhalten (links Text, rechts spezielle Inhaltselemente).
- Anpassungsmöglichkeiten über das CMS.

## Abgrenzung:
- Keine dynamische Interaktion.

## Akzeptanzkriterien:
- Das Modul passt sich an verschiedene Bildschirmgrößen an und ist vollständig im CMS anpassbar.

**Comment by robocopklaus** [comment]
Hier wäre es noch interessant, wenn die Headline innerhalb der Stickyspalte ist.

**Comment by robocopklaus** [comment]
![Image](https://github.com/user-attachments/assets/b471de58-dcee-42c1-b095-83c9f78469e1)

Bei manchen Zwischengrößen wird die Schrift abgeschnitten -> Erfolgsgeschichten

**Comment by robocopklaus** [comment]
Wenn ich `Alignment: Center` wähle im Backend, dann ist das Aligment weiterhin links
