### ISSUE TITLE
Implement Website Header

### ISSUE THREAD

**Issue by JimSeven** [21stdigital/21st.digital#273]
<img width="549" alt="image" src="https://github.com/user-attachments/assets/0dfc9fd1-846f-44f0-9e7e-308d6e4dc6b3">

## Problem:
Die Website benötigt einen Header, um die Navigationselemente und andere wichtige Inhalte wie Logos und Links einheitlich darzustellen. Der Header ist im Design vorgegeben, die technische Implementierung fehlt jedoch.

## User Story:
Als Besucher der Website möchte ich einen klar strukturierten Header sehen, der mir den Zugriff auf die wichtigsten Navigationspunkte und Inhalte der Seite ermöglicht.

## Vorhaben:
- Implementierung eines flexiblen Headers gemäß den Design-Vorgaben.
- Integration der Hauptnavigation, des Logos und optionaler Links (z. B. zu Social Media oder Kontakt).
- Der Header soll responsive sein und sich an verschiedene Bildschirmgrößen anpassen (Desktop, Tablet, Mobile).

## Abgrenzung:
- Keine komplexen Animationen oder Interaktionen wie Dropdown-Menüs (werden in separaten Stories behandelt).

## Akzeptanzkriterien:
- Der Header wird auf allen Bildschirmgrößen korrekt dargestellt.
- Alle Inhalte (Logo, Navigation, Links) sind vollständig über das CMS anpassbar.
- Die Struktur und das Design entsprechen den Vorgaben.

**Comment by robocopklaus** [comment]
@JimSeven dynamisch machen

**Comment by robocopklaus** [comment]
- Evtl. sticky machen
- "Termin vereinbaren" öffnet sich noch im neuen Tab statt über ein Modal
