### ISSUE TITLE
Implement Website Footer

### ISSUE THREAD

**Issue by JimSeven** [21stdigital/21st.digital#274]
<img width="552" alt="image" src="https://github.com/user-attachments/assets/f4c591d3-ef19-4bb8-9ebd-dc41e3ac1ca6">

## Problem:
Ein Footer muss für die Website implementiert werden, um zusätzliche Informationen und Links wie Impressum, Datenschutz oder Social Media zu platzieren. Das Design für den Footer liegt bereits vor, die Programmierung fehlt noch.

## User Story:
Als Besucher der Website möchte ich einen Footer sehen, der zusätzliche Informationen und Links bereitstellt, die leicht zugänglich und übersichtlich strukturiert sind.

## Vorhaben:
- Implementierung des Footers gemäß den Design-Vorgaben.
- Platz für wichtige Links wie Impressum, Datenschutz und Social Media Icons.
- Flexibler Aufbau, sodass Inhalte und Links über das CMS angepasst werden können.
- Der Footer soll sich responsiv an verschiedene Bildschirmgrößen anpassen.

## Abgrenzung:
- Keine dynamischen Elemente wie Formulare oder interaktive Karten.

## Akzeptanzkriterien:
- Der Footer wird auf allen Bildschirmgrößen korrekt dargestellt.
- Inhalte und Links können vollständig über das CMS angepasst werden.
- Das Design entspricht den Vorgaben und ist flexibel erweiterbar.

**Comment by robocopklaus** [comment]
@JimSeven dynamisch machen

**Comment by robocopklaus** [comment]
@JimSeven  Kontakt, Datenschutz und Impressum sind noch hardgecoded. Hier bräuchten wir nur Datenschutz und Impressum als Nav-Item
