### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by robocopklaus** [21stdigital/21st.digital#5]
# Problem

Die aktuelle Startseite der Website repräsentiert weder das moderne Design noch die inhaltliche Ausrichtung unserer Firma angemessen. Dies könnte potenzielle Kunden davon abhalten, Kontakt für Projekte aufzunehmen.

# User Story

Als potenzieller Kunde möchte ich auf der Startseite schnell verstehen können, wer die Firma ist und was sie anbietet, damit ich einschätzen kann, ob sie für mein Projekt geeignet ist.

# Vorhaben

Entwicklung einer neuen Startseite, die ein modernes Design und aktuelle Inhalte präsentiert. Die Seite soll eine klare und prägnante Beschreibung der Firma und ihrer Dienstleistungen enthalten. Im Zentrum stehen dabei visuell ansprechende Case Studies von erfolgreich umgesetzten Projekten. Ein weiterer Bereich soll namhafte Kunden durch eine Logo Wall hervorheben, um Vertrauen und Professionalität zu signalisieren. Zudem sollen Links zu detaillierteren Case Studies und zum Impressum integriert werden. Ferner soll als CTA immer die Kontaktaufnahme präsent sein.

# Abgrenzung

Die Story fokussiert sich ausschließlich auf die Startseite. Andere Unterseiten der Website.

# Akzeptanzkriterien

- Die Startseite zeigt eine eindeutige und knappe Beschreibung der Firma und ihrer Kernkompetenzen.
- Case Studies von Schlüsselprojekten sind visuell ansprechend dargestellt und leicht zugänglich.
- Die Logo Wall mit namhaften Kunden ist prominent platziert und unterstützt das Vertrauen in die Firma.
- Es gibt klare, funktionierende Links zu den Case Studies und zum Impressum.
- Die Seite ist responsiv und bietet auf verschiedenen Geräten eine optimale Benutzererfahrung.

**Comment by Sm1lEE** [comment]
Die Inhalte der Home finde ich sehr gut strukturiert und verständlich. Laut aktuellem Stand gibt es auch mindestens 2 CTAs zur Kontaktaufnahme. Ich überlege, ob noch etwas "Persönliches" fehlt, wie z. B. unsere Namen oder ein Bild von uns. Das fand ich auf der jetzigen Live-Seite ganz charmant. Oder auch weitere Kontaktinformationen/Adressdaten.

Das könnte man auch in den Footer integrieren, dann haben wir es auf allen Seiten.

Was meint ihr dazu? Sollten wir uns in irgendeiner Art und Weise konkreter darstellen?

**Comment by CptCompiler** [comment]
@Sm1lEE ich denke, dass auf dieser seite dann noch mehr über uns dargestellt wird. #16 

Trotzdem finde ich deine Überlegung nicht schlecht, dass die Startseite noch etwas persönlicher wird.

**Comment by robocopklaus** [comment]
@CptCompiler @Sm1lEE ja, genau. dafür gäbe es dann nach dem MVP eine eigene seite

**Comment by robocopklaus** [comment]
[wireframe.pdf](https://github.com/21stdigital/21st.digital/files/15187288/wireframe.pdf)
